import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import { Inter } from 'next/font/google';
import './globals.css';
import SectionContainer from '@/components/sectionContainer';

const inter = Inter({ subsets: ['latin'] });
const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  // variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white pl-[calc(100vw-100%)] text-black antialiased dark:bg-gray-950 dark:text-white ${space_grotesk.className}`}>
        <SectionContainer>
          <div className="flex h-screen flex-col justify-between ">{children}</div>
        </SectionContainer>
      </body>
    </html>
  );
}
