import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import { Inter } from 'next/font/google';
import './globals.css';
import SectionContainer from '@/components/sectionContainer';
import BottomNavigation from '@/components/bottomNav';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });
const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  // variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen relative  ${space_grotesk.className}`}>
        <div className="flex flex-col justify-between">
          <BottomNavigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}

//pl-[calc(100vw-100%)
